import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";
//import Header from "@/components/Partial/Header";
//import Aside from "@/components/Partial/Aside";
//import { ToastContainer } from 'react-toastify';
//import 'react-toastify/dist/ReactToastify.css';
//import Banner from "@/components/Partial/Banner";
const inter = Inter({ subsets: ["latin"] });
import { SessionProvider } from "next-auth/react"

export const metadata: Metadata = {
  title: "Legitem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
            <Head>
              <link rel="manifest" href='/manifest.json' sizes="any" />
              <link rel="icon" href="/icon-512x512.png" />
              <title>Legitem</title>
            </Head>
            <body>
              {children}
            </body>
          </html>
    
  );
}
