import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";
import ReduxWrapper from '@/components/ReduxWrapper';
import LoadEruda from './LoadEruda';
const inter = Inter({ subsets: ["latin"] });
import { SessionProvider } from "next-auth/react"
export const metadata: Metadata = {
  title: "Legitem",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
            <Head>
              <link rel="manifest" href='/manifest.json' sizes="any" />
              <link rel="icon" href="/icon-512x512.png" />
              <title>Legitem</title>
            </Head>
            <body>
              <LoadEruda/>
              {children}
            </body>
          </html>
    
  );
}
