import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";
import Header from "@/components/Partial/Header";
import Aside from "@/components/Partial/Aside";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Legitem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="manifest" href='/manifest.json' sizes="any" />
        <link rel="icon" href="/icon-512x512.png" />
        <title>Legitem</title>
      </Head>
      <body className={inter.className}>
      <Script
          type="module"
          src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
          strategy="lazyOnload"
        />
      <div className="flex flex-wrap h-[100vh]">
        <div className="flex flex-1 justify-center h-[8vh] align-center bg-gradient-to-t from-lime-500 via-lime-700 to-lime-800 z-50">
          <Header/>
        </div>
        {children}
        <Aside />
      </div>
        </body>
    </html>
  );
}
